[programs.localnet]
dapp_starter = "6fv1QAQC5t5DtCpqNf78sf2EW5XGj2YHPqpkwdxP7tiU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./.wallets/hoangphuc.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/dapp-starter.ts"
